### ISSUE TITLE
Make install not working.

### ISSUE THREAD

**Issue by redetzky** [xwiimote/xwiimote-bindings#5]
Complete!
[nolan@nolanfedoraaio xwiimote]$ ./autogen.sh
libtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, `build-aux'.
libtoolize: linking file`build-aux/ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIR, `m4'.
libtoolize: linking file`m4/libtool.m4'
libtoolize: linking file `m4/ltoptions.m4'
libtoolize: linking file`m4/ltsugar.m4'
libtoolize: linking file `m4/ltversion.m4'
libtoolize: linking file`m4/lt~obsolete.m4'
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking minix/config.h usability... no
checking minix/config.h presence... no
checking for minix/config.h... no
checking whether it is safe to define **EXTENSIONS**... yes
checking for special C compiler options needed for large files... no
checking for _FILE_OFFSET_BITS value needed for large files... no
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking for style of include used by make... GNU
checking whether make supports nested variables... yes
checking how to create a pax tar archive... gnutar
checking dependency style of gcc... gcc3
checking whether make supports nested variables... (cached) yes
checking for gcc... (cached) gcc
checking whether we are using the GNU C compiler... (cached) yes
checking whether gcc accepts -g... (cached) yes
checking for gcc option to accept ISO C89... (cached) none needed
checking whether gcc understands -c and -o together... (cached) yes
checking for gcc option to accept ISO C99... none needed
checking whether ln -s works... yes
checking for ar... ar
checking the archiver (ar) interface... ar
checking how to print strings... printf
checking for a sed that does not truncate output... /usr/bin/sed
checking for fgrep... /usr/bin/grep -F
checking for ld used by gcc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking the maximum length of command line arguments... 1572864
checking whether the shell understands some XSI constructs... yes
checking whether the shell understands "+="... yes
checking how to convert x86_64-unknown-linux-gnu file names to x86_64-unknown-linux-gnu format... func_convert_file_noop
checking how to convert x86_64-unknown-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /usr/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /usr/bin/nm -B output from gcc object... ok
checking for sysroot... no
checking for mt... no
checking if : is a manifest tool... no
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... no
checking for gcc option to produce PIC... -fPIC -DPIC
checking if gcc PIC flag -fPIC -DPIC works... yes
checking if gcc static flag -static works... no
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... yes
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for UDEV... yes
checking for NCURSES... yes
checking whether to build with debugging on... no
checking for doxygen... no
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating libxwiimote.pc
config.status: creating doc/Doxyfile
config.status: creating config.h
config.status: executing depfiles commands
config.status: executing libtool commands
configure: Build configuration:

```
           prefix: /usr/local
      exec-prefix: ${prefix}
           libdir: ${exec_prefix}/lib
       includedir: ${prefix}/include

            debug: no
          doxygen: no

    Run "make" to start compilation process
```

[nolan@nolanfedoraaio xwiimote]$ make
make --no-print-directory all-recursive
Making all in .
  CC       lib/libxwiimote_la-core.lo
  CC       lib/libxwiimote_la-monitor.lo
  CCLD     libxwiimote.la
ar: `u' modifier ignored since`D' is the default (see `U')
  CC       tools/xwiishow-xwiishow.o
  CCLD     xwiishow
  CC       tools/xwiidump-xwiidump.o
  CCLD     xwiidump
[nolan@nolanfedoraaio xwiimote]$ make install
Making install in .
 /usr/bin/mkdir -p '/usr/local/lib'
 /bin/sh ./libtool   --mode=install /usr/bin/install -c   libxwiimote.la '/usr/local/lib'
libtool: install: /usr/bin/install -c .libs/libxwiimote.so.2.0.0 /usr/local/lib/libxwiimote.so.2.0.0
/usr/bin/install: cannot create regular file '/usr/local/lib/libxwiimote.so.2.0.0': Permission denied
Makefile:611: recipe for target 'install-libLTLIBRARIES' failed
make[2]: **\* [install-libLTLIBRARIES] Error 1
Makefile:1263: recipe for target 'install-am' failed
make[1]: **\* [install-am] Error 2
Makefile:959: recipe for target 'install-recursive' failed
make: **\* [install-recursive] Error 1
[nolan@nolanfedoraaio xwiimote]$ make
make --no-print-directory all-recursive
Making all in .
[nolan@nolanfedoraaio xwiimote]$ make
make --no-print-directory all-recursive
Making all in .
[nolan@nolanfedoraaio xwiimote]$ make install
Making install in .
 /usr/bin/mkdir -p '/usr/local/lib'
 /bin/sh ./libtool   --mode=install /usr/bin/install -c   libxwiimote.la '/usr/local/lib'
libtool: install: /usr/bin/install -c .libs/libxwiimote.so.2.0.0 /usr/local/lib/libxwiimote.so.2.0.0
/usr/bin/install: cannot create regular file '/usr/local/lib/libxwiimote.so.2.0.0': Permission denied
Makefile:611: recipe for target 'install-libLTLIBRARIES' failed
make[2]: **\* [install-libLTLIBRARIES] Error 1
Makefile:1263: recipe for target 'install-am' failed
make[1]: **\* [install-am] Error 2
Makefile:959: recipe for target 'install-recursive' failed
make: **\* [install-recursive] Error 1

**Comment by dvdhrm** [comment]
`libtool: install: /usr/bin/install -c .libs/libxwiimote.so.2.0.0 /usr/local/lib/libxwiimote.so.2.0.0
/usr/bin/install: cannot create regular file '/usr/local/lib/libxwiimote.so.2.0.0': Permission denied`

Just read what it says: Permission denied. You need to be root to install a package into your system.

**Comment by nadenislamarre** [comment]
Or change the prefix. I guess that configure --prefix=$HOME/app should work
without root access. If keeping default, root is required only to the make
install commande.

**Comment by PureTryOut** [comment]
This is a user problem, not a bug. This can be closed @nadenislamarre
