### ISSUE TITLE
unexpected token `XWIIMOTE,'

### ISSUE THREAD

**Issue by ottk3** [xwiimote/xwiimote-bindings#6]
Hi there

I've got some troubles getting xwiimote-bindings compiled to use them with Python.
I'm using Debian 'jessie' and got the packages _xwiimote_, _libxwiimote2_ and _libxwiimote-dev_ installed.

When I try to use `./autogen.sh` it breaks with the following error:

```
checking whether to build static libraries... yes
./configure: line 12815: syntax error near unexpected token `XWIIMOTE,'
./configure: line 12815: `PKG_CHECK_MODULES(XWIIMOTE, libxwiimote)'
```

It's expecting _libxwiimote_ instead of _libxwiimote2_?
Thanks for any help.

**Comment by nadenislamarre** [comment]
not sure, but i thing you should not run autogen.sh which should do more
than just required for compilation.

just ./configure --prefix=/anywhere && make && make install

clean the directory, untar again and check it woks please.

2015-10-07 16:45 GMT+02:00 Sven Rojek notifications@github.com:

**Comment by ottk3** [comment]
If I clone the current repository `./configure` is not available since the **configure** file is missing?

OK, my bad... missed creating the configure file with `autoreconf -i`, but I get the same error.
Using: `gcc (Raspbian 4.9.2-10) 4.9.2`

**Comment by nadenislamarre** [comment]
sorry, i thought you started from the .tar.gz package.
From the git repository,
i run ./autogen.sh, and it works on my ubuntu.
I've libxwiimote-dev not installed so it stopped later saying the
libxwiimote is missing but at least, configure is generated.

what is your version of autoreconf ?

mine is :
nicolas@setsouko:~/dev/xwiimote-bindings$ autoreconf --version
autoreconf (GNU Autoconf) 2.69

i guess you're version is too old.

2015-10-08 9:47 GMT+02:00 Sven Rojek notifications@github.com:

**Comment by ottk3** [comment]
Thanks for your reply. My autoreconf version is also 2.69 -  might there be a problem with the arm architecture?

```
pi@raspi:/home/pi# autoreconf --version
autoreconf (GNU Autoconf) 2.69
```

Where would i find the _.tar.gz package_?

**Comment by nadenislamarre** [comment]
is it  a raspbian or where can i get the img to try on my pi ?

**Comment by ottk3** [comment]
~~Yes, it's the default [Raspian 'jessie'](https://www.raspberrypi.org/downloads/raspbian/).~~

It's actually an upgraded  [Minibian](http://sourceforge.net/projects/minibian/) - I will try the default Raspbian Image.

**Comment by nadenislamarre** [comment]
from a fresh raspian jessie just installed from the link below, the
following commands work

sudo apt-get install autoconf libtool libxwiimote-dev swig libpython2.7-dev
cd /tmp
git clone https://github.com/dvdhrm/xwiimote-bindings.git
cd xwiimote-bindings
./autogen.sh

unfortunatly, libxwiimote-dev is no up to date on the raspbian,
and xwiimote-bindings requires a more recent one
so :
make # fails

so, we get the last xwiimote version :
sudo apt-get remove libxwiimote-dev
sudo apt-get autoremove
sudo apt-get install ncurses-dev libudev-dev

cd /tmp
git clone https://github.com/dvdhrm/xwiimote.git
cd xwiimote
./autogen.sh
./configure --prefix=/tmp/install
make
make install

cd xwiimote-bindings
make clean
export PKG_CONFIG_PATH=/tmp/install/lib/pkgconfig
./configure --prefix=/tmp/install
make
make install

everything installed in /tmp/install, perhaps you should use an other
directory, but choose one to not install with the debian system

2015-10-09 12:19 GMT+02:00 Sven Rojek notifications@github.com:

**Comment by ottk3** [comment]
Thank you! Worked perfectly with the default Raspbian, seems to be a problem with the Minibian build.

**Comment by markierer** [comment]
I had exactly the same error message like ottk3. In my case it was the missing package pkg-config.
`sudo apt-get install pkg-config` solved the problem.
